---
- import_tasks: tasks/host_start.yml
  tags: [up,deploy]

- import_tasks: tasks/vm_create.yml
  tags: [deploy]

- import_tasks: tasks/vm_clone.yml
  tags: [clone]

- import_tasks: tasks/vm_update.yml
  tags: [deploy,clone,update]
  
- import_tasks: tasks/vm_start.yml
  tags: [start,up,deploy,clone]

- import_tasks: tasks/vm_stop.yml
  tags: [stop,halt]

- import_tasks: tasks/vm_delete.yml
  tags: [delete]

- import_tasks: tasks/host_shutdown.yml
  tags: [halt]