---
- name: Clone template to new VM
  proxmox_kvm:
    node: "{{ pve.prox_node }}"
    api_user: "{{ pve.prox_user }}"
    api_password: "{{ pve.prox_password }}"
    api_host: "{{ pve.host_ip }}"
    clone: "{{ item.value.template | default(vms_def.template) }}"
    full: "{{ vms_def.clone_full }}"
    name: "{{ item.value.name }}"
    storage: "{{ item.value.storage | default(vms_def.storage) }}" 
    timeout: "{{ pve.clone_timeout }}"
  register: vm_id
  loop: "{{ vms | dict2items }}"
...